### ISSUE TITLE
mean is not correct

### ISSUE THREAD

**Issue by omveersharmanet** [MustafaSaraoglu/TreeGenerator#1]
it think in the Maneuver class , 
''mean = state.s + state.s + state.speed*deltaT;'' 
this is not correct it should be 
mean =state.s + state.speed*deltaT;

**Comment by MustafaSaraoglu** [comment]
Thank you very much! Yes, you are right. Could you send a pull request with the change that you suggested? So I can accept and merge it and your contribution would be honored 👍
